name: TempSpawn
version: '${project.version}'
main: me.arimas.tempspawn.TempSpawn
author: arimas
description: A plugin that allows players to set and reset their own temporary spawn points, with commands for admins.

commands:
  settempspawn:
    description: Set a temporary spawn point for yourself or another player.
    usage: /<command> [player]
    aliases: [sts]
    permission: tempspawn.set
  resettempspawn:
    description: Reset your temporary spawn point or that of another player.
    usage: /<command> [player]
    aliases: [rts]
    permission: tempspawn.reset

permissions:
  tempspawn.set:
    description: Permission to set your own temporary spawn point.
    default: true
  tempspawn.adminset:
    description: Permission to set another player's temporary spawn point.
    default: op
  tempspawn.reset:
    description: Permission to reset your own temporary spawn point.
    default: true
  tempspawn.adminreset:
    description: Permission to reset another player's temporary spawn point.
    default: op
