name: TemporarySpawn
main: me.arimas.temporaryspawn.TemporarySpawn
version: 1.6
author: Aremas
api-version: 1.13
description: Allows players to set and reset their own temporary spawn points, as well as letting admins set and reset other players temporary spawn points.
commands:
  silentsetplayertempspawn:
    description: Set a temporary spawn point for a player without informing them.
    usage: "Usage: /<command> [player(s)] [x] [y] [z] [yaw] [pitch] [world]"
    permission: temporaryspawn.silentsetplayertempspawn
    aliases: quietsetplayertempspawn
  silentresetplayertempspawn:
    description: Reset the temporary spawn point of a player without informing them.
    usage: "Usage: /<command> [player(s)]"
    permission: temporaryspawn.silentresetplayertempspawn
    aliases: quietresetplayertempspawn
  setplayertempspawn:
    description: Set a temporary spawn point for a player.
    usage: "Usage: /<command> [player(s)] [x] [y] [z] [yaw] [pitch] [world]"
    permission: temporaryspawn.setplayertempspawn
    aliases:
      - settempspawn
      - setempspawn
  resetplayertempspawn:
    description: Reset the temporary spawn point of a player.
    usage: "Usage: /<command> [player(s)]"
    permission: temporaryspawn.resetplayertempspawn
  tempspawn:
    description: Set a temporary spawn point for yourself at your location.
    usage: "Usage: /<command>"
    permission: temporaryspawn.tempspawn
  resettempspawn:
    description: Reset your temporary spawn point.
    usage: "Usage: /<command>"
    permission: temporaryspawn.resettempspawn
    aliases: resetempspawn
permissions:
  temporaryspawn.silentsetplayertempspawn:
    description: Allows players to set a temporary spawn point for other players without informing them.
    default: op
  temporaryspawn.silentresetplayertempspawn:
    description: Allows players to reset the temporary spawn point of other players without informing them.
    default: op
  temporaryspawn.setplayertempspawn:
    description: Allows players to set a temporary spawn point for other players.
    default: op
  temporaryspawn.resetplayertempspawn:
    description: Allows players to reset the temporary spawn point of other players.
    default: op
  temporaryspawn.tempspawn:
    description: Allows players to set a temporary spawn point for themselves.
    default: true
  temporaryspawn.resettempspawn:
    description: Allows players to reset their own temporary spawn point.
    default: true